name: Update protocol and Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: skip tests
        run: sed -i  's/MVN=mvn/MVN=mvn -DskipTests/' Makefile

      - name: Download latest protocol
        run: make download-latest-protocol

      - name: Update protocol
        run: make update-protocol

      - name: Package
        run: make build-all-modules

      - name: Undo skip tests
        run: git checkout Makefile

      - name: List Changes
        run: git diff --name-status

      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "protocol-update"
          commit-message: "Update interface to reflect latest Devtools protocol"
          title: Devtools protocol update
          body: "Automatic protocol update to latest version"

